service: acg-neptune-api

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-plugin-vpc-eni-cleanup

provider:
  name: aws
  runtime: nodejs12.x
  vpc:
    securityGroupIds:
      - ${cf:${self:custom.neptuneStackName}.SecurityGroup}
    subnetIds:
      - ${cf:${self:custom.neptuneStackName}.Subnet1}
      - ${cf:${self:custom.neptuneStackName}.Subnet2}
  stage: dev
  region: us-east-1
  environment:
    CLUSTER_ENDPOINT: ${cf:${self:custom.neptuneStackName}.DBClusterEndpoint}
    ROLE_ARN: ${cf:${self:custom.neptuneStackName}.NeptuneLoadFromS3RoleArn}
    LOADER_S3_BUCKET: ${cf:${self:custom.rekognitionStackName}.S3Bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - neptune-db:*
      Resource:
        - "arn:aws:neptune-db:${self:provider.region}:#{AWS::AccountId}:${cf:${self:custom.neptuneStackName}.DBClusterResourceId}/*"
    - Effect: Allow # for serverless-plugin-vpc-eni-cleanup to prevent long stack removal time
      Action:
        - ec2:DeleteNetworkInterface
        - ec2:DetachNetworkInterface
        - ec2:DescribeNetworkInterfaces
      Resource:
        - "*"
custom:
  webpackIncludeModules:
    forceInclude:
      - gremlin
      - isomorphic-fetch
  neptuneStackName: acg-neptune-db-dev
  rekognitionStackName: acg-rekognition-data-dev

functions:
  query:
    handler: query.query
    timeout: 20
    events:
      - http:
          path: query
          method: get
          cors: true
          request:
            parameters:
              queryStrings:
                imageId: true
                threshold: true
                hops: true

  loader:
    handler: loader.load
    timeout: 30
    events:
      - http:
          path: loader
          method: post
